server:
  port: 10080

spring:
  mvc:
    servlet:
      load-on-startup: 1
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  aop:
    proxy-target-class: true
  main:
    lazy-initialization: false
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8
  servlet:
    multipart:
      max-file-size: 5MB


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDel
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    path: /data/logs/yx-shgd
  config: classpath:logback-spring.xml

request:
  log:
    enable: true

file:
  path: /data/file/
  mapper: /file/

